name: Laravel Pint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: "laravel-pint"
          uses: aglipanci/laravel-pint-action@203c2fea1102e51381b31e153de5ea7296626c72
          with:
            preset: laravel
            verboseMode: true
            pintVersion: 1.2.1
